apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: acejs/itickets-auth
          env: # set env variables from k8s node
            - name: JWT_KEY #name assign as pod env variable
              valueFrom:
                secretKeyRef:
                  name: jwt-secret #secret container
                  key: JWT_KEY #secret targeted key

---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  type: ClusterIP
  selector:
    app: auth # this service has to find a set of pods with this label "app: auth"
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
